name: MCraft
version: '${version}'
main: com.dontkonwdream.mcraft.mcraft.MCraft
api-version: 1.18
authors: [ JiuYue ]
description: 现代化的工作台
website: https://dontkonwdream.com

commands:
  dreamtest:
    description: The First Command.
    usage: /<dreamtest>
    permission-message: 你没有权限
