name: DCrafting
version: '1.0-SNAPSHOT'
main: org.dream.crafting.dcrafting.DCrafting
api-version: 1.18
authors: [ BlueDream ]
description: An ehchanced crafting table for Minecraft Java Edition.
website: https://dreamedworker.github.io
